import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header/Header";
import MiniHeader from "./components/Header/MiniHeader";
import Footer from "./components/Footer";
import ReduxProvider from "./store/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Amazon Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gray-300">
        <ReduxProvider>
          <Header />
          <MiniHeader />
          {children}
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
